# Generated by Django 2.1.4 on 2018-12-10 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('port', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skils',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_title', models.CharField(max_length=50)),
                ('skill_icon', models.ImageField(upload_to='skills/')),
            ],
        ),
        migrations.AlterField(
            model_name='projects',
            name='project_image',
            field=models.ImageField(upload_to='projects/'),
        ),
    ]
