# Generated by Django 2.1.4 on 2018-12-10 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('port', '0003_auto_20181210_0228'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Projects',
            new_name='Project',
        ),
        migrations.RenameModel(
            old_name='Skills',
            new_name='Skill',
        ),
    ]
